### ISSUE TITLE
Lets pack this as an AppImage

### ISSUE THREAD

**Issue by nandgator** [lliurex/lliurex-store#2]
Can we have this as an AppImage itself?

Helpful resource: https://github.com/appimagecrafters/appimage-builder

**Comment by juanma1980** [comment]
Hi, thanks for your interest.
Actually the lliurex-store is something lliurex specific and is being reworked too. We want to make it distro agnostic before distribute it as an appimage because that is the nature of appimages, and being distro-specific is not an option for an appimage.
Again thanks for your suggestion and stay tunned for news
